/*
  Auto-generated by Spline
*/
import React from "react";
import Spline from "@splinetool/react-spline";

const Test = () => {
  return (
    <>
      <Spline scene="https://prod.spline.design/YoMZCjq7uAQV3Hx5/scene.splinecode" />
      ;
    </>
  );
};

export default Test;
